worker_processes auto;

events {
  worker_connections 4096;
}

stream {
  upstream velocity_tcp {
    server velocity:25565;
  }

  server {
    listen 25565;
    proxy_pass velocity_tcp;
    proxy_timeout 1h;
    proxy_connect_timeout 10s;
  }
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                  '$status $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" "$http_x_forwarded_for"';

  access_log /var/log/nginx/access.log main;
  sendfile on;
  keepalive_timeout 65;
  client_max_body_size 50m;

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  include /etc/nginx/conf.d/*.conf;
}
